import { Public_Sans } from "next/font/google";
import "./globals.css";
import ContextProviders from "@/services/context";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const publicSans = Public_Sans({
    subsets: ["latin"],
    variable: "--font-public-sans",
    display: "swap",
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <ContextProviders>
                <body className={`${publicSans.variable}`}>
                    <ToastContainer />
                    {children}
                </body>
            </ContextProviders>
        </html>
    );
}
